In [2]:
import numpy as np
from numpy import exp, array, random, dot

In [4]:
2*random.random((3,1))-1

array([[0.66457987],
       [0.58595096],
       [0.83851009]])

In [8]:
class NeuralNetwork:
  def __init__(self):
    random.seed(2)
    self.weights = 2*random.random((3,1))-1

  def sigmoid(self,x):
    return 1/(1+exp(-x))

  def sigmoid_derivative(self, sigmoid_op):
    return sigmoid_op*(1-sigmoid_op)

  def netinputop(self,inputs):
    return self.sigmoid(dot(inputs,self.weights))

  def train(self, training_inputs, training_outputs, number_iterations):
    for iteration in range(number_iterations):
      #pass the training data to neural networks
      output = self.netinputop(training_inputs)
      #calculate error
      error = training_outputs-output
      #calculate adjustment
      adjustment = dot(training_inputs.T,error*self.sigmoid_derivative(output))
      #change the weight
      self.weights=self.weights+adjustment


In [9]:
neural_net = NeuralNetwork()

print('Random weights before training')
print(neural_net.weights)

training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_outputs=np.array([[0,1,1,0]]).T

neural_net.train(training_inputs,training_outputs,10000)

print('Random weights after training')
print(neural_net.weights)

Random weights before training
[[-0.1280102 ]
 [-0.94814754]
 [ 0.09932496]]
Random weights after training
[[ 9.67282529]
 [-0.20892653]
 [-4.62890667]]


In [10]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [11]:
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [12]:
print('test data')
print('The output is,', neural_net.netinputop(np.array([1,0,0])))

test data
The output is, [0.99993703]
