In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#step -1 zero rank tensor
tensor1=tf.constant(4)
print(tensor1)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
# rank one tensor
tensor_rank1=tf.constant([2.0,9.0,7.0])
tensor_rank1

#1D array

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 9., 7.], dtype=float32)>

In [4]:
# create a matrix/ rank2 tensor
tensor_rank2=tf.constant([[0,1,2],[2,3,4],[4,5,6]])
tensor_rank2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [5]:
# convert to numpy array
tensor_rank2.numpy()

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]], dtype=int32)

In [7]:
a = tf.constant([[1,2],[3,4]])
b= tf.constant([[5,6],[7,8]])

print(tf.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [8]:
print(tf.multiply(a,b))

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [9]:
#maximum value of the tensor
b=tf.constant([[5,6],[7,8]])
print(tf.reduce_max(b))

tf.Tensor(8, shape=(), dtype=int32)


In [10]:
print(tf.math.argmax(b))

tf.Tensor([1 1], shape=(2,), dtype=int64)


In [11]:
# broadcasting in tensors
x=tf.constant([1,2,3])
y=tf.constant(2)
print(tf.multiply(x,2))
print(tf.multiply(x,y))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [12]:
# reshape the tensor
b=tf.constant([[5,6,6],[7,8,9]])
print(b.shape)

(2, 3)


In [13]:
new_tensor=tf.reshape(b,[3,2])
new_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [6, 7],
       [8, 9]], dtype=int32)>

In [16]:
new_tensor.ndim

2

## Ragged Tensor - variable number of elements along some axes

In [18]:

list1=[[3,4,5],[5],[6,7]]


tensor4=tf.ragged.constant(list1)
tensor4

<tf.RaggedTensor [[3, 4, 5], [5], [6, 7]]>

In [19]:
tensor4.shape

TensorShape([3, None])

In [20]:
tensor4.ragged_rank

1

In [22]:
list2=[[[3,4],[5]],[[4],[5,6,7]]]


tensor5=tf.ragged.constant(list1)
tensor5

<tf.RaggedTensor [[[3, 4], [5]],
 [[4], [5, 6, 7]]]>

In [23]:
tensor5.shape

TensorShape([2, None, None])

In [24]:
tensor5.ragged_rank

2